type: object
allOf:
  - $ref: ../../schedule/_types/product.yaml
  - type: object
    properties:
      _id:
        type: string
      name:
        type: string

    required:
      - _id
      - name
