type: object
allOf:
  - $ref: ../../schedule/_types/product.yaml
  - type: object
    properties:
      scheduleId:
        type: string
      scheduleName:
        type: string

    required:
      - scheduleId
      - scheduleName
