type: object
properties:
  _id:
    type: string
  hidden:
    type: boolean
  image:
    $ref: "./image.yaml"
  productId:
    type: integer
  title:
    type: string
  active:
    type: boolean
    default: true
  buffertime:
    type: integer
  duration:
    type: integer
required:
  - _id
  - hidden
  - productId
  - users
  - title
  - active
  - buffertime
  - duration
