type: object
properties:
  productId:
    type: number
  title:
    type: string
  variants:
    type: array
    items:
      type: object
      properties:
        variantId:
          type: number
        title:
          type: string
        price:
          type: string
        duration:
          type: object
          properties:
            value:
              type: number
            metafieldId:
              type: number
          required:
            - value
            - metafieldId
      required:
        - variantId
        - duration
        - title
        - price

required:
  - productId
  - variants
  - title
