type: array
items:
  type: object
  properties:
    location:
      type: string
    locationType:
      type: string
      enum: [home, commercial, destination, virtual]
  required:
    - location
    - locationType
