type: object
properties:
  productId:
    type: number
  variants:
    type: array
    items:
      type: object
      properties:
        variantId:
          type: number
        duration:
          type: object
          properties:
            value:
              type: number
            metafieldId:
              type: number
          required:
            - value
            - metafieldId
      required:
        - variantId
        - duration

required:
  - productId
  - variants
