type: array
items:
  type: object
  properties:
    location:
      type: string
    locationType:
      type: string
      enum: [origin, destination]
    originType:
      type: string
      enum: [home, commercial]
  required:
    - location
    - locationType
    - originType
