type: object
properties:
  productId:
    type: number
  variants:
    type: array
    items:
      type: object
      properties:
        variantId:
          type: number
        duration:
          type: number
      required:
        - variantId
        - duration

required:
  - productId
  - variants
