openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Auth
        - My Account
        - User
        - Shift
servers:
  - url: http://localhost:7071/api
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ErrorResponse:
      $ref: "./responses/error.yaml"
    UserResponse:
      $ref: "./paths/user/responses/user-response.yaml"
    UsersResponse:
      $ref: "./paths/user/responses/users-response.yaml"

  schemas:
    # errors
    ErrorModel:
      $ref: "./schemas/error-model.yaml"
    ValidationError:
      $ref: "./schemas/validation-error.yaml"
    MessageError:
      $ref: "./schemas/message-error.yaml"

    # auth
    AuthLoginResponse:
      $ref: "./paths/auth/schemas/login-response.yaml"
    AuthLoginRequest:
      $ref: "./paths/auth/schemas/login-request.yaml"
    AuthPasswordResponse:
      $ref: "./paths/auth/schemas/receive-password-response.yaml"
    AuthPasswordRequest:
      $ref: "./paths/auth/schemas/receive-password-request.yaml"

    # user
    UserCreateOrUpdateModel:
      $ref: "./paths/user/schemas/user-create.yaml"
    UserModel:
      $ref: "./paths/user/schemas/user-model.yaml"
    UserResponse:
      $ref: "./paths/user/schemas/user-response.yaml"
    UsersResponse:
      $ref: "./paths/user/schemas/users-response.yaml"

    # shift
    ShiftCreateGroupModel:
      $ref: "./paths/shift/schemas/shift-create-group.yaml"
    ShiftCreateModel:
      $ref: "./paths/shift/schemas/shift-create.yaml"
    ShiftDestroyModel:
      $ref: "./paths/shift/schemas/shift-destroy.yaml"
    ShiftModel:
      $ref: "./paths/shift/schemas/shift-model.yaml"

paths:
  # auth
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/receive-password:
    $ref: "./paths/auth/receive-password.yaml"

  # my account
  /my-account:
    $ref: "./paths/my/account.yaml"

  # user
  /users:
    $ref: "./paths/user/get-all-users.yaml"

  /user/create-user-api:
    $ref: "./paths/user/create-user-api.yaml"

  /user:
    $ref: "./paths/user/create-user.yaml"

  /user/{id}:
    $ref: "./paths/user/get-by-id-or-update-user.yaml"

  # shift
  /user/{userId}/shifts:
    $ref: "./paths/shift/get-all.yaml"

  /user/{userId}/shift:
    $ref: "./paths/shift/create-and-update.yaml"

tags:
  - name: Auth
    description: Login and reset password
  - name: My Account
    description: Manage logged in user data.
  - name: User
    description: Manage users..
  - name: Shift
    description: Manage shifts for user.
