openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
servers:
  - url: http://localhost:7071/api
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    MesssageErrorResponse:
      $ref: "./responses/error.yaml"

    ValidationErrorResponse:
      $ref: "./responses/validation.yaml"

  schemas:
    ZodErrors:
      $ref: "./schemas/zod-errors.yaml"
    User:
      $ref: "./schemas/user.yaml"
paths:
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/receive-password:
    $ref: "./paths/auth/receive-password.yaml"

  /create-user:
    $ref: "./paths/user/create-user.yaml"

  /my/account:
    $ref: "./paths/my/account.yaml"
