openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
servers:
  - url: http://localhost:7071/api/
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ResourceNotFoundRequest:
      $ref: "./responses/resource-not-found.yaml"

    BadRequest:
      $ref: "./responses/bad.yaml"

  parameters:
    shop:
      $ref: "./parameters/shop.yaml"
  schemas:
    ZodIssueCode:
      $ref: "./schemas/zod-issue-code.yaml"

    Staff:
      $ref: "./schemas/staff.yaml"
paths:
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/receive-password:
    $ref: "./paths/auth/receive-password.yaml"

  /my/account:
    $ref: "./paths/my/account.yaml"
