openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  contact:
    name: jamal Soueidan
    email: jamal@soueidan.com
    url: "https://github.com/jamalsoueidan"
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Schedule
servers:
  - url: https://booking-shopify-api.azurewebsites.net/api
components:
  responses:
    BadResponse:
      $ref: "./responses/bad.yaml"
    ForbiddenResponse:
      $ref: "./responses/forbidden.yaml"
    NotFoundResponse:
      $ref: "./responses/not-found.yaml"
    UnauthorizedResponse:
      $ref: "./responses/unauthorized.yaml"

  schemas:
    Errors:
      $ref: "./schemas/errors.yaml"
    #User:
    #  $ref: paths/user/_types/user.yaml
    Destroy:
      $ref: paths/schedule/_types/destroy.yaml
    Day:
      $ref: paths/schedule/_types/day.yaml
    Interval:
      $ref: paths/schedule/_types/interval.yaml
    Slot:
      $ref: paths/schedule/_types/slot.yaml
    Product:
      $ref: paths/schedule/_types/product.yaml
    ProductBookingPeriod:
      $ref: paths/schedule/_types/product-booking-period.yaml
    ProductBookingUnit:
      $ref: paths/schedule/_types/product-booking-unit.yaml
    ProductNoticePeriod:
      $ref: paths/schedule/_types/product-notice-period.yaml
    ProductNoticeUnit:
      $ref: paths/schedule/_types/product-notice-unit.yaml
    Schedule:
      $ref: paths/schedule/_types/schedule.yaml

    # Schedule
    ScheduleCreateBody:
      $ref: paths/schedule/create/body.yaml
    ScheduleCreateResponse:
      $ref: paths/schedule/create/response.yaml
    ScheduleDestroyResponse:
      $ref: paths/schedule/destroy/response.yaml
    ScheduleListResponse:
      $ref: paths/schedule/list/response.yaml
    ScheduleGetResponse:
      $ref: paths/schedule/get/response.yaml
    ScheduleUpdateResponse:
      $ref: paths/schedule/update/response.yaml
    ScheduleUpdateBody:
      $ref: paths/schedule/update/body.yaml

    # Slots
    ScheduleSlotsUpdateResponse:
      $ref: paths/schedule/slots/update/response.yaml
    ScheduleSlotsUpdateBody:
      $ref: paths/schedule/slots/update/body.yaml

    # Product
    CustomerProductUpsertResponse:
      $ref: paths/customer/product/upsert/response.yaml
    CustomerProductUpsertBody:
      $ref: paths/customer/product/upsert/body.yaml
    CustomerProductDestroyResponse:
      $ref: paths/customer/product/destroy/response.yaml
    CustomerProductGetResponse:
      $ref: paths/customer/product/get/response.yaml

    # Booking
    CustomerBooking:
      $ref: paths/customer/booking/_types/booking.yaml
    CustomerBookingGetResponse:
      $ref: paths/customer/booking/get/response.yaml
    CustomerBookingListResponse:
      $ref: paths/customer/booking/list/response.yaml

    # Customer
    Customer:
      $ref: paths/customer/_types/customer.yaml
    CustomerProductList:
      $ref: paths/customer/_types/product.yaml
    CustomerProductAvailability:
      $ref: paths/customer/_types/availability.yaml
    CustomerIsBusinessResponse:
      $ref: paths/customer/is-business/response.yaml
    CustomersListResponse:
      $ref: paths/customer/list/response.yaml
    CustomerGetResponse:
      $ref: paths/customer/get/response.yaml
    CustomerUpdateResponse:
      $ref: paths/customer/update/response.yaml
    CustomerUpdateBody:
      $ref: paths/customer/update/body.yaml
    CustomerUpsertResponse:
      $ref: paths/customer/upsert/response.yaml
    CustomerUpsertBody:
      $ref: paths/customer/upsert/body.yaml
    CustomerProductListIdsResponse:
      $ref: paths/customer/products/list-ids/response.yaml
    CustomerProductListResponse:
      $ref: paths/customer/products/list/response.yaml
    CustomerProductAvailabilityResponse:
      $ref: paths/customer/product/availability/response.yaml

    CustomerProffesion:
      $ref: paths/user/_types/professions.yaml
    # User
    #UserGetResponse:
    #  $ref: paths/user/get/response.yaml
paths:
  # User
  #/user/{username}:
  #  $ref: "./paths/user/user.yaml"

  #/users:
  #  $ref: "./paths/user/list/index.yaml"

  # Customer
  /customers:
    $ref: "paths/customer/list/index.yaml"

  /customer/{identifier}:
    $ref: "./paths/customer/customer.yaml"

  /customer/{identifier}/update:
    $ref: "./paths/customer/update/index.yaml"

  /customer/{customerId}/isBusiness:
    $ref: "./paths/customer/is-business/index.yaml"

  /customer/{customerId}/products:
    $ref: "./paths/customer/products/list/index.yaml"
  /customer/{customerId}/products/ids:
    $ref: "./paths/customer/products/list-ids/index.yaml"

  /customer/{customerId}/product/availability:
    $ref: paths/customer/product/availability/index.yaml

  /customer/{customerId}/product/{productId}:
    $ref: paths/customer/product/product.yaml

  /customer/{customerId}/booking/{orderId}:
    $ref: paths/customer/booking/get/index.yaml

  /customer/{customerId}/bookings:
    $ref: paths/customer/booking/list/index.yaml

  # schedule
  /customer/{customerId}/schedule:
    $ref: "./paths/schedule/create/index.yaml"
  /customer/{customerId}/schedules:
    $ref: "./paths/schedule/list/index.yaml"
  /customer/{customerId}/schedule/{scheduleId}:
    $ref: "./paths/schedule/schedule.yaml"

  /customer/{customerId}/schedule/{scheduleId}/slots:
    $ref: paths/schedule/slots/update/index.yaml
