openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  contact:
    name: jamal Soueidan
    email: jamal@soueidan.com
    url: "https://github.com/jamalsoueidan"
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Schedule
servers:
  - url: https://booking-shopify-api.azurewebsites.net/api
components:
  responses:
    BadResponse:
      $ref: "./responses/bad.yaml"
    ForbiddenResponse:
      $ref: "./responses/forbidden.yaml"
    NotFoundResponse:
      $ref: "./responses/not-found.yaml"
    UnauthorizedResponse:
      $ref: "./responses/unauthorized.yaml"

  schemas:
    Errors:
      $ref: "./schemas/errors.yaml"
    MetaItem:
      $ref: paths/meta/_types/item.yaml

    # Product
    CustomerProductBase:
      $ref: paths/customer/schedule/_types/base-product.yaml
    CustomerProduct:
      $ref: paths/customer/schedule/_types/product.yaml
    CustomerProductBookingPeriod:
      $ref: paths/customer/schedule/_types/product-booking-period.yaml
    CustomerProductBookingUnit:
      $ref: paths/customer/schedule/_types/product-booking-unit.yaml
    CustomerProductNoticePeriod:
      $ref: paths/customer/schedule/_types/product-notice-period.yaml
    CustomerProductNoticeUnit:
      $ref: paths/customer/schedule/_types/product-notice-unit.yaml
    CustomerProductLocations:
      $ref: paths/customer/schedule/_types/product-locations.yaml
    CustomerProductUpsertResponse:
      $ref: paths/customer/product/upsert/response.yaml
    CustomerProductUpsertBody:
      $ref: paths/customer/product/upsert/body.yaml
    CustomerProductDestroyResponse:
      $ref: paths/customer/product/destroy/response.yaml
    CustomerProductGetResponse:
      $ref: paths/customer/product/get/response.yaml

    # Schedule
    CustomerScheduleDestroy:
      $ref: paths/customer/schedule/_types/destroy.yaml
    CustomerScheduleSlotDay:
      $ref: paths/customer/schedule/_types/day.yaml
    CustomerScheduleSlotInterval:
      $ref: paths/customer/schedule/_types/interval.yaml
    CustomerScheduleSlot:
      $ref: paths/customer/schedule/_types/slot.yaml

    CustomerSchedule:
      $ref: paths/customer/schedule/_types/schedule.yaml
    CustomerScheduleCreateBody:
      $ref: paths/customer/schedule/create/body.yaml
    CustomerScheduleCreateResponse:
      $ref: paths/customer/schedule/create/response.yaml
    CustomerScheduleDestroyResponse:
      $ref: paths/customer/schedule/destroy/response.yaml
    CustomerScheduleListResponse:
      $ref: paths/customer/schedule/list/response.yaml
    CustomerScheduleGetResponse:
      $ref: paths/customer/schedule/get/response.yaml
    CustomerScheduleUpdateResponse:
      $ref: paths/customer/schedule/update/response.yaml
    CustomerScheduleUpdateBody:
      $ref: paths/customer/schedule/update/body.yaml

    # Slots
    CustomerScheduleSlotsUpdateResponse:
      $ref: paths/customer/schedule/slots/update/response.yaml
    CustomerScheduleSlotsUpdateBody:
      $ref: paths/customer/schedule/slots/update/body.yaml

    # Booking
    CustomerBooking:
      $ref: paths/customer/booking/_types/booking.yaml
    CustomerBookingGetResponse:
      $ref: paths/customer/booking/get/response.yaml
    CustomerBookingListResponse:
      $ref: paths/customer/booking/list/response.yaml

    # Customer
    CustomerProductList:
      $ref: paths/customer/_types/product.yaml
    CustomerProductAvailability:
      $ref: paths/customer/_types/availability.yaml
    CustomerIsBusinessResponse:
      $ref: paths/customer/is-business/response.yaml
    CustomerStatus:
      $ref: paths/customer/status/payload.yaml
    CustomerStatusResponse:
      $ref: paths/customer/status/response.yaml
    CustomerGetResponse:
      $ref: paths/customer/get/response.yaml
    CustomerUpdateResponse:
      $ref: paths/customer/update/response.yaml
    CustomerUpdateBody:
      $ref: paths/customer/update/body.yaml
    CustomerUpsertResponse:
      $ref: paths/customer/upsert/response.yaml
    CustomerUpsertBody:
      $ref: paths/customer/upsert/body.yaml
    CustomerProductListIdsResponse:
      $ref: paths/customer/products/list-ids/response.yaml
    CustomerProductListResponse:
      $ref: paths/customer/products/list/response.yaml
    CustomerProductAvailabilityResponse:
      $ref: paths/customer/product/availability/response.yaml

    CustomerLocationDestinationIsDefault:
      $ref: paths/customer/location/_types/location-destination-is-default.yaml
    CustomerLocationOriginIsDefault:
      $ref: paths/customer/location/_types/location-origin-is-default.yaml
    CustomerLocationGetAllLocationOrigin:
      $ref: paths/customer/location/get-all-origins/location-origin.yaml
    CustomerLocationGetAllRepsonse:
      $ref: paths/customer/location/get-all-origins/response.yaml
    CustomerLocationCreateOriginBody:
      $ref: paths/customer/location/create-origin/body.yaml
    CustomerLocationCreateOriginResponse:
      $ref: paths/customer/location/create-origin/response.yaml
    CustomerLocationCreateDestinationBody:
      $ref: paths/customer/location/create-destination/body.yaml
    CustomerLocationCreateDestinationResponse:
      $ref: paths/customer/location/create-destination/response.yaml
    CustomerLocationListResponse:
      $ref: paths/customer/location/list/response.yaml
    CustomerLocationGetResponse:
      $ref: paths/customer/location/get/response.yaml
    CustomerLocationUpdateDestinationBody:
      $ref: paths/customer/location/update-destination/body.yaml
    CustomerLocationUpdateDestinationResponse:
      $ref: paths/customer/location/update-destination/response.yaml
    CustomerLocationUpdateOriginBody:
      $ref: paths/customer/location/update-origin/body.yaml
    CustomerLocationUpdateOriginResponse:
      $ref: paths/customer/location/update-origin/response.yaml
    CustomerLocationAddResponse:
      $ref: paths/customer/location/add/response.yaml
    CustomerLocationRemoveResponse:
      $ref: paths/customer/location/remove/response.yaml
    CustomerLocationSetDefaultResponse:
      $ref: paths/customer/location/set-default/response.yaml

    # User
    User:
      $ref: paths/user/_types/user.yaml
    UserSchedules:
      $ref: paths/user/_types/user_with_schedules.yaml
    UserSchedule:
      $ref: paths/user/_types/schedule_with_locations.yaml
    UserScheduleProduct:
      $ref: paths/user/_types/product_with_locations.yaml
    UserScheduleGetResponse:
      $ref: paths/user/schedule/get/response.yaml
    UserGetResponse:
      $ref: paths/user/get/response.yaml
    UsersListResponse:
      $ref: paths/user/list/response.yaml
    UsersProfessionsResponse:
      $ref: paths/user/professions/response.yaml

    # Location
    LocationOrigin:
      $ref: paths/customer/location/_types/location-origin.yaml
    LocationDestination:
      $ref: paths/customer/location/_types/location-destination.yaml
    LocationCoordinates:
      $ref: paths/location/_types/coordinates.yaml
    LocationTravelTime:
      $ref: paths/location/_types/travel-time.yaml
    LocationGetCoordinatesResponse:
      $ref: paths/location/get-coordinates/response.yaml
    LocationGetTravelTimeResponse:
      $ref: paths/location/get-travel-time/response.yaml
    LocationValidateAddressResponse:
      $ref: paths/location/validate-address/response.yaml

paths:
  # User
  /user/{username}:
    $ref: "./paths/user/user.yaml"
  /user/{username}/schedule/{scheduleId}/location/{locationId}:
    $ref: "./paths/user/schedule/get/index.yaml"

  /users/professions:
    $ref: "./paths/user/professions/index.yaml"

  /users:
    $ref: "./paths/user/list/index.yaml"

  # Customer
  /customer/{customerId}:
    $ref: "./paths/customer/customer.yaml"
  /customer/{customerId}/status:
    $ref: "./paths/customer/status/index.yaml"
  /customer/{customerId}/update:
    $ref: "./paths/customer/update/index.yaml"
  /customer/{customerId}/isBusiness:
    $ref: "./paths/customer/is-business/index.yaml"
  /customer/{customerId}/products:
    $ref: "./paths/customer/products/list/index.yaml"
  /customer/{customerId}/products/ids:
    $ref: "./paths/customer/products/list-ids/index.yaml"
  /customer/{customerId}/product/availability:
    $ref: "paths/customer/product/availability/index.yaml"
  /customer/{customerId}/product/{productId}:
    $ref: "paths/customer/product/product.yaml"
  /customer/{customerId}/booking/{orderId}:
    $ref: "paths/customer/booking/get/index.yaml"
  /customer/{customerId}/bookings:
    $ref: "paths/customer/booking/list/index.yaml"

  # schedule
  /customer/{customerId}/schedule:
    $ref: "./paths/customer/schedule/create/index.yaml"
  /customer/{customerId}/schedules:
    $ref: "./paths/customer/schedule/list/index.yaml"
  /customer/{customerId}/schedule/{scheduleId}:
    $ref: "./paths/customer/schedule/schedule.yaml"

  /customer/{customerId}/schedule/{scheduleId}/slots:
    $ref: "paths/customer/schedule/slots/update/index.yaml"

  # meta
  /meta/professions:
    $ref: "./paths/meta/professions/index.yaml"
  /meta/specialties:
    $ref: "./paths/meta/specialties/index.yaml"

  # locations
  /customer/{customerId}/locations/get-all-origins:
    $ref: "./paths/customer/location/get-all-origins/index.yaml"

  /customer/{customerId}/locations/destination:
    $ref: "./paths/customer/location/create-destination/index.yaml"
  /customer/{customerId}/location/{locationId}/destination:
    $ref: "./paths/customer/location/update-destination/index.yaml"

  /customer/{customerId}/locations/origin:
    $ref: "./paths/customer/location/create-origin/index.yaml"
  /customer/{customerId}/location/{locationId}/origin:
    $ref: "./paths/customer/location/update-origin/index.yaml"

  /customer/{customerId}/location/{locationId}/setDefault:
    $ref: "./paths/customer/location/set-default/index.yaml"

  /customer/{customerId}/location/{locationId}:
    $ref: "./paths/customer/location/add-remove-get.yaml"

  /customer/{customerId}/locations: # list
    $ref: "./paths/customer/location/list/index.yaml"

  /location/get-coordinates:
    $ref: "./paths/location/get-coordinates/index.yaml"
  /location/validate-address:
    $ref: "./paths/location/validate-address/index.yaml"
  /location/get-travel-time:
    $ref: "./paths/location/get-travel-time/index.yaml"
