openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Auth
        - My Account
        - User
servers:
  - url: http://localhost:7071/api
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      flows:
      scopes:
        read:user: Access user data
        read:admin: Access admin data
        write:user: Modify user data
        write:admin: Modify admin data

  responses:
    ErrorResponse:
      $ref: "./responses/error.yaml"
    UserResponse:
      $ref: "./paths/user/responses/user-response.yaml"
    UsersResponse:
      $ref: "./paths/user/responses/users-response.yaml"

  schemas:
    # errors
    ErrorModel:
      $ref: "./schemas/error-model.yaml"
    ValidationError:
      $ref: "./schemas/validation-error.yaml"
    MessageError:
      $ref: "./schemas/message-error.yaml"

    # auth
    AuthLoginResponse:
      $ref: "./paths/auth/schemas/login-response.yaml"
    AuthLoginRequest:
      $ref: "./paths/auth/schemas/login-request.yaml"
    AuthPasswordResponse:
      $ref: "./paths/auth/schemas/receive-password-response.yaml"
    AuthPasswordRequest:
      $ref: "./paths/auth/schemas/receive-password-request.yaml"

    # user
    UserModel:
      $ref: "./paths/user/schemas/user.yaml"
    UserResponse:
      $ref: "./paths/user/schemas/user-response.yaml"
    UsersResponse:
      $ref: "./paths/user/schemas/users-response.yaml"

paths:
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/receive-password:
    $ref: "./paths/auth/receive-password.yaml"

  /user/create-user-api:
    $ref: "./paths/user/create-user-api.yaml"

  /my-account:
    $ref: "./paths/my/account.yaml"

  /users:
    $ref: "./paths/user/get-all-users.yaml"

  /user:
    $ref: "./paths/user/create-user.yaml"

  /user/{id}:
    $ref: "./paths/user/user-id.yaml"

tags:
  - name: Auth
    description: Login and reset password
  - name: My Account
    description: Logged in user can receive his data
  - name: User
    description: Manage users when logged in.
