openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  contact:
    name: jamal Soueidan
    email: jamal@soueidan.com
    url: "https://github.com/jamalsoueidan"
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Schedule
servers:
  - url: https://booking-shopify-api.azurewebsites.net/api
components:
  responses:
    BadResponse:
      $ref: "./responses/bad.yaml"
    ForbiddenResponse:
      $ref: "./responses/forbidden.yaml"
    NotFoundResponse:
      $ref: "./responses/not-found.yaml"
    UnauthorizedResponse:
      $ref: "./responses/unauthorized.yaml"

  schemas:
    Errors:
      $ref: "./schemas/errors.yaml"
    MetaItem:
      $ref: paths/meta/_types/item.yaml

    # Upload
    CustomerUploadResourceURLResponse:
      $ref: paths/customer/upload/resource-url/response.yaml

    # Product
    CustomerProductBase:
      $ref: paths/customer/schedule/_types/base-product.yaml
    CustomerProduct:
      $ref: paths/customer/schedule/_types/product.yaml
    CustomerProductBookingPeriod:
      $ref: paths/customer/schedule/_types/product-booking-period.yaml
    CustomerProductBookingUnit:
      $ref: paths/customer/schedule/_types/product-booking-unit.yaml
    CustomerProductNoticePeriod:
      $ref: paths/customer/schedule/_types/product-notice-period.yaml
    CustomerProductNoticeUnit:
      $ref: paths/customer/schedule/_types/product-notice-unit.yaml
    CustomerProductLocations:
      $ref: paths/customer/schedule/_types/product-locations.yaml
    CustomerProductUpsertResponse:
      $ref: paths/customer/product/upsert/response.yaml
    CustomerProductUpsertBody:
      $ref: paths/customer/product/upsert/body.yaml
    CustomerProductDestroyResponse:
      $ref: paths/customer/product/destroy/response.yaml
    CustomerProductGetResponse:
      $ref: paths/customer/product/get/response.yaml

    # Schedule
    CustomerScheduleDestroy:
      $ref: paths/customer/schedule/_types/destroy.yaml
    CustomerScheduleSlotDay:
      $ref: paths/customer/schedule/_types/day.yaml
    CustomerScheduleSlotInterval:
      $ref: paths/customer/schedule/_types/interval.yaml
    CustomerScheduleSlot:
      $ref: paths/customer/schedule/_types/slot.yaml

    CustomerSchedule:
      $ref: paths/customer/schedule/_types/schedule.yaml
    CustomerScheduleCreateBody:
      $ref: paths/customer/schedule/create/body.yaml
    CustomerScheduleCreateResponse:
      $ref: paths/customer/schedule/create/response.yaml
    CustomerScheduleDestroyResponse:
      $ref: paths/customer/schedule/destroy/response.yaml
    CustomerScheduleListResponse:
      $ref: paths/customer/schedule/list/response.yaml
    CustomerScheduleGetResponse:
      $ref: paths/customer/schedule/get/response.yaml
    CustomerScheduleUpdateResponse:
      $ref: paths/customer/schedule/update/response.yaml
    CustomerScheduleUpdateBody:
      $ref: paths/customer/schedule/update/body.yaml

    # Slots
    CustomerScheduleSlotsUpdateResponse:
      $ref: paths/customer/schedule/slots/update/response.yaml
    CustomerScheduleSlotsUpdateBody:
      $ref: paths/customer/schedule/slots/update/body.yaml

    # Booking
    CustomerBooking:
      $ref: paths/customer/booking/_types/booking.yaml
    CustomerBookingGetResponse:
      $ref: paths/customer/booking/get/response.yaml
    CustomerBookingListResponse:
      $ref: paths/customer/booking/list/response.yaml

    # Order
    CustomerOrder:
      $ref: paths/customer/order/_types/order.yaml
    CustomerOrderMoney:
      $ref: paths/customer/order/_types/money.yaml
    CustomerOrderAddress:
      $ref: paths/customer/order/_types/address.yaml
    CustomerOrderClient:
      $ref: paths/customer/order/_types/client.yaml
    CustomerOrderDiscount:
      $ref: paths/customer/order/_types/discount.yaml
    CustomerOrderLineItemProperties:
      $ref: paths/customer/order/_types/properties.yaml
    CustomerOrderSimpleLineItem:
      $ref: paths/customer/order/_types/simple-line-item.yaml
    CustomerOrderCustomer:
      $ref: paths/customer/order/_types/customer.yaml
    CustomerOrderLineItem:
      $ref: paths/customer/order/_types/line-item.yaml
    CustomerOrderRefund:
      $ref: paths/customer/order/_types/refund.yaml
    CustomerOrderShipping:
      $ref: paths/customer/order/_types/shipping.yaml
    CustomerOrderFulfillment:
      $ref: paths/customer/order/_types/fulfillment.yaml
    CustomerOrderGetResponse:
      $ref: paths/customer/order/get/response.yaml
    CustomerOrderListResponse:
      $ref: paths/customer/order/list/response.yaml

    # Customer
    CustomerProductList:
      $ref: paths/customer/_types/product.yaml
    CustomerIsBusinessResponse:
      $ref: paths/customer/is-business/response.yaml
    CustomerStatus:
      $ref: paths/customer/status/payload.yaml
    CustomerStatusResponse:
      $ref: paths/customer/status/response.yaml
    CustomerGetResponse:
      $ref: paths/customer/get/response.yaml
    CustomerCreateResponse:
      $ref: paths/customer/create/response.yaml
    CustomerCreateBody:
      $ref: paths/customer/create/body.yaml
    CustomerUpdateResponse:
      $ref: paths/customer/update/response.yaml
    CustomerUpdateBody:
      $ref: paths/customer/update/body.yaml
    CustomerProductListIdsResponse:
      $ref: paths/customer/product/list-ids/response.yaml
    CustomerProductListResponse:
      $ref: paths/customer/product/list/response.yaml

    CustomerLocation:
      $ref: paths/customer/location/_types/location.yaml
    CustomerLocationIsDefault:
      $ref: paths/customer/location/_types/location-is-default.yaml
    CustomerLocationGetAllOriginsRepsonse:
      $ref: paths/customer/location/get-all-origins/response.yaml
    CustomerLocationCreateBody:
      $ref: paths/customer/location/create/body.yaml
    CustomerLocationCreateResponse:
      $ref: paths/customer/location/create/response.yaml
    CustomerLocationListResponse:
      $ref: paths/customer/location/list/response.yaml
    CustomerLocationGetResponse:
      $ref: paths/customer/location/get/response.yaml
    CustomerLocationUpdateBody:
      $ref: paths/customer/location/update/body.yaml
    CustomerLocationUpdateResponse:
      $ref: paths/customer/location/update/response.yaml
    CustomerLocationAddResponse:
      $ref: paths/customer/location/add/response.yaml
    CustomerLocationRemoveResponse:
      $ref: paths/customer/location/remove/response.yaml
    CustomerLocationSetDefaultResponse:
      $ref: paths/customer/location/set-default/response.yaml

    # User
    UserUsernameTakenResponse:
      $ref: paths/user/username-taken/response.yaml
    User:
      $ref: paths/user/_types/user.yaml
    UserScheduleWithLocations:
      $ref: paths/user/schedule/_types/schedule-with-locations.yaml
    UserScheduleProductWithLocations:
      $ref: paths/user/schedule/_types/product-with-locations.yaml
    UserLocationGetResponse:
      $ref: paths/user/location/get/response.yaml
    UserProductsGetResponse:
      $ref: paths/user/products/get/response.yaml
    UserProductsListByLocationResponse:
      $ref: paths/user/products/list-by-location/response.yaml
    UserProductsGetProductsBody:
      $ref: paths/user/products/get-products/body.yaml
    UserProductsGetProductsResponse:
      $ref: paths/user/products/get-products/response.yaml
    UserProductsListByScheduleResponse:
      $ref: paths/user/products/list-by-schedule/response.yaml
    UserScheduleGetByLocationResponse:
      $ref: paths/user/schedule/get-by-location/response.yaml
    UserScheduleGetByProductIdResponse:
      $ref: paths/user/schedule/get-by-product/response.yaml
    UserGetResponse:
      $ref: paths/user/get/response.yaml
    UsersListResponse:
      $ref: paths/user/list/response.yaml
    UsersProfessionsResponse:
      $ref: paths/user/professions/response.yaml

    # UserAvailability
    UserAvailabilitySlot:
      $ref: paths/user/availability/_types/slot.yaml
    UserAvailability:
      $ref: paths/user/availability/_types/availability.yaml
    UserAvailabilitySingle:
      $ref: paths/user/availability/get/availability.yaml
    UserAvailabilityGetBody:
      $ref: paths/user/availability/get/body.yaml
    UserAvailabilityGeResponse:
      $ref: paths/user/availability/get/response.yaml
    UserAvailabilityMulti:
      $ref: paths/user/availability/generate/availability.yaml
    UserAvailabilityGenerateBody:
      $ref: paths/user/availability/generate/body.yaml
    UserAvailabilityGenerateResponse:
      $ref: paths/user/availability/generate/response.yaml

    # Location
    LocationCoordinates:
      $ref: paths/location/_types/coordinates.yaml
    LocationTravelTime:
      $ref: paths/location/_types/travel-time.yaml
    LocationGetCoordinatesResponse:
      $ref: paths/location/get-coordinates/response.yaml
    LocationGetTravelTimeResponse:
      $ref: paths/location/get-travel-time/response.yaml
    LocationValidateAddressResponse:
      $ref: paths/location/validate-address/response.yaml

    # Shipping
    Shipping:
      $ref: paths/shipping/_types/shipping.yaml
    ShippingBody:
      $ref: paths/shipping/_types/body.yaml
    ShippingCreateResponse:
      $ref: paths/shipping/create/response.yaml
    ShippingCalculateResponse:
      $ref: paths/shipping/calculate/response.yaml
    ShippingGetResponse:
      $ref: paths/shipping/get/response.yaml

    # Orchestrators
    UploadBody:
      $ref: paths/orchestrators/upload/body.yaml
    UploadResponse:
      $ref: paths/orchestrators/upload/response.yaml

    # Products
    ProductsGetUsersImageBody:
      $ref: paths/products/get-users-image/body.yaml
    ProductsGetUsersImageResponse:
      $ref: paths/products/get-users-image/response.yaml
    ProductsGetUsersImage:
      $ref: paths/products/get-users-image/product_users.yaml
    ProductsGetUsersByVariantResponse:
      $ref: paths/products/get-users-by-variant/response.yaml
    ProductsGetUsersByVariant:
      $ref: paths/products/get-users-by-variant/user.yaml
paths:
  # Products
  /products/get-users-image:
    $ref: "./paths/products/get-users-image/index.yaml"
  /products/get-users-by-variant:
    $ref: "./paths/products/get-users-by-variant/index.yaml"

  # User
  /user/{username}/username-taken:
    $ref: "./paths/user/username-taken/index.yaml"
  /user/{username}:
    $ref: "./paths/user/user.yaml"
  /user/{username}/products/{productHandle}:
    $ref: "./paths/user/products/get/index.yaml"
  /user/{username}/products:
    $ref: "./paths/user/products/list-by-schedule/index.yaml"
  /user/{username}/product/{productHandle}/location/{locationId}:
    $ref: "./paths/user/products/list-by-location/index.yaml"
  /user/{username}/products/location/{locationId}:
    $ref: "./paths/user/products/get-products/index.yaml"
  /user/{username}/schedule/get-by-product-id/{productHandle}:
    $ref: paths/user/schedule/get-by-product/index.yaml
  /user/{username}/schedules/locations:
    $ref: "./paths/user/schedule/list/index.yaml"
  /user/{username}/location/{locationId}:
    $ref: "./paths/user/location/get/index.yaml"
  /user/{username}/schedule/{scheduleId}/location/{locationId}:
    $ref: "./paths/user/schedule/get-by-location/index.yaml"
  /users/professions:
    $ref: "./paths/user/professions/index.yaml"
  /user/{username}/availability/{locationId}/generate:
    $ref: "paths/user/availability/generate/index.yaml"
  /user/{username}/availability/{locationId}/get:
    $ref: "paths/user/availability/get/index.yaml"

  /users:
    $ref: "./paths/user/list/index.yaml"

  # Customer
  /customer/{customerId}/upload/resource-url:
    $ref: paths/customer/upload/resource-url/index.yaml
  /customer/{customerId}:
    $ref: "./paths/customer/customer.yaml"
  /customer/{customerId}/status:
    $ref: "./paths/customer/status/index.yaml"
  /customer:
    $ref: "./paths/customer/create/index.yaml"
  /customer/{customerId}/isBusiness:
    $ref: "./paths/customer/is-business/index.yaml"
  /customer/{customerId}/products:
    $ref: "./paths/customer/product/list/index.yaml"
  /customer/{customerId}/products/ids:
    $ref: "./paths/customer/product/list-ids/index.yaml"
  /customer/{customerId}/product/{productId}:
    $ref: "paths/customer/product/product.yaml"
  /customer/{customerId}/booking/{orderId}:
    $ref: "paths/customer/booking/get/index.yaml"
  /customer/{customerId}/bookings:
    $ref: "paths/customer/booking/list/index.yaml"
  /customer/{customerId}/orders:
    $ref: "paths/customer/order/list/index.yaml"
  /customer/{customerId}/lineItemId/{lineItemId}:
    $ref: "paths/customer/order/get/index.yaml"

  # schedule
  /customer/{customerId}/schedule:
    $ref: "./paths/customer/schedule/create/index.yaml"
  /customer/{customerId}/schedules:
    $ref: "./paths/customer/schedule/list/index.yaml"
  /customer/{customerId}/schedule/{scheduleId}:
    $ref: "./paths/customer/schedule/schedule.yaml"

  /customer/{customerId}/schedule/{scheduleId}/slots:
    $ref: "paths/customer/schedule/slots/update/index.yaml"

  # meta
  /meta/professions:
    $ref: "./paths/meta/professions/index.yaml"
  /meta/specialties:
    $ref: "./paths/meta/specialties/index.yaml"

  # locations
  /customer/{customerId}/locations/get-all-origins:
    $ref: "./paths/customer/location/get-all-origins/index.yaml"
  /customer/{customerId}/location/{locationId}/setDefault:
    $ref: "./paths/customer/location/set-default/index.yaml"
  /customer/{customerId}/location/{locationId}:
    $ref: "./paths/customer/location/get-delete-update-add.yaml"
  /customer/{customerId}/locations:
    $ref: "./paths/customer/location/create-list.yaml"
  /location/get-coordinates:
    $ref: "./paths/location/get-coordinates/index.yaml"
  /location/validate-address:
    $ref: "./paths/location/validate-address/index.yaml"
  /location/get-travel-time:
    $ref: "./paths/location/get-travel-time/index.yaml"

  # shipping
  /shipping/create:
    $ref: "./paths/shipping/create/index.yaml"
  /shipping/calculate:
    $ref: "./paths/shipping/calculate/index.yaml"
  /shipping/{shippingId}:
    $ref: "./paths/shipping/get/index.yaml"

  # Orchestrators
  /orchestrators/upload:
    $ref: "./paths/orchestrators/upload/index.yaml"
