openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: http://
  contact:
    name: jamal Soueidan
    email: jamal@soueidan.com
    url: "https://github.com/jamalsoueidan"
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Schedule
servers:
  - url: https://booking-shopify-api.azurewebsites.net/api
components:
  responses:
    BadResponse:
      $ref: "./responses/bad.yaml"
    ForbiddenResponse:
      $ref: "./responses/forbidden.yaml"
    NotFoundResponse:
      $ref: "./responses/not-found.yaml"
    UnauthorizedResponse:
      $ref: "./responses/unauthorized.yaml"

  schemas:
    Errors:
      $ref: "./schemas/errors.yaml"
    User:
      $ref: paths/user/_types/user.yaml

    Destroy:
      $ref: paths/schedule/_types/destroy.yaml
    Day:
      $ref: paths/schedule/_types/day.yaml
    Interval:
      $ref: paths/schedule/_types/interval.yaml
    Slot:
      $ref: paths/schedule/_types/slot.yaml
    Product:
      $ref: paths/schedule/_types/product.yaml
    Schedule:
      $ref: paths/schedule/_types/schedule.yaml

    # Schedule
    ScheduleCreateBody:
      $ref: paths/schedule/create/body.yaml
    ScheduleCreateResponse:
      $ref: paths/schedule/create/response.yaml
    ScheduleDestroyResponse:
      $ref: paths/schedule/destroy/response.yaml
    ScheduleListResponse:
      $ref: paths/schedule/list/response.yaml
    ScheduleGetResponse:
      $ref: paths/schedule/get/response.yaml
    ScheduleUpdateResponse:
      $ref: paths/schedule/update/response.yaml
    ScheduleUpdateBody:
      $ref: paths/schedule/update/body.yaml

    # Slots
    ScheduleSlotsUpdateResponse:
      $ref: paths/schedule/slots/update/response.yaml
    ScheduleSlotsUpdateBody:
      $ref: paths/schedule/slots/update/body.yaml

    # Product
    ScheduleProductCreateOrUpdateResponse:
      $ref: paths/schedule/product/create-or-update/response.yaml
    ScheduleProductCreateOrUpdateBody:
      $ref: paths/schedule/product/create-or-update/body.yaml
    ScheduleProductDestroyResponse:
      $ref: paths/schedule/product/destroy/response.yaml
    ScheduleProductGetResponse:
      $ref: paths/schedule/product/get/response.yaml

    # User
    UserCreateOrUpdateResponse:
      $ref: paths/user/create-or-update/response.yaml
    UserCreateOrUpdateBody:
      $ref: paths/user/create-or-update/body.yaml
    UserGetResponse:
      $ref: paths/user/get/response.yaml
paths:
  /customer/{customerId}:
    $ref: "./paths/user/user.yaml"

  # schedule
  /customer/{customerId}/schedule:
    $ref: "./paths/schedule/create/index.yaml"
  /customer/{customerId}/schedules:
    $ref: "./paths/schedule/list/index.yaml"
  /customer/{customerId}/schedule/{scheduleId}:
    $ref: "./paths/schedule/schedule.yaml"

  /customer/{customerId}/schedule/{scheduleId}/slots:
    $ref: paths/schedule/slots/update/index.yaml

  /customer/{customerId}/schedule/{scheduleId}/product/{productId}:
    $ref: paths/schedule/product/product.yaml

tags:
  - name: Schedule
    description: Schedule
