openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
servers:
  - url: http://localhost:7071/api
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    ErrorResponse:
      $ref: "./responses/error.yaml"

  schemas:
    ErrorModel:
      $ref: "./schemas/error-model.yaml"
    ValidationError:
      $ref: "./schemas/validation-error.yaml"
    MessageError:
      $ref: "./schemas/message-error.yaml"
    UserModel:
      $ref: "./paths/user/schemas/user.yaml"
    AuthLoginSuccess:
      $ref: "./paths/auth/schemas/login-success.yaml"
paths:
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/receive-password:
    $ref: "./paths/auth/receive-password.yaml"

  /create-user:
    $ref: "./paths/user/create-user-api.yaml"

  /my-account:
    $ref: "./paths/my/account.yaml"

  /user:
    $ref: "./paths/user/user.yaml"

  /user/{id}:
    $ref: "./paths/user/user-id.yaml"
