type: object
properties:
  _id:
    type: string
  hidden:
    type: boolean
  imageUrl:
    type: string
  productId:
    type: integer
  users:
    type: array
    items:
      $ref: "./user.yaml"
  title:
    type: string
  active:
    type: boolean
    default: true
  buffertime:
    type: integer
  duration:
    type: integer
required:
  - _id
  - hidden
  - imageUrl
  - productId
  - users
  - title
  - active
  - buffertime
  - duration
