type: object
properties:
  productId:
    type: number
  duration:
    oneOf:
      - type: string
      - type: number
  breakTime:
    oneOf:
      - type: string
      - type: number
  noticePeriod:
    $ref: "./product-notice-period.yaml"
  bookingPeriod:
    $ref: "./product-booking-period.yaml"
required:
  - productId
  - duration
  - breakTime
  - noticePeriod
  - bookingPeriod
