type: object
properties:
  productId:
    type: number
  duration:
    oneOf:
      - type: string
      - type: number
  breakTime:
    oneOf:
      - type: string
      - type: number
  noticePeriod:
    type: object
    properties:
      value:
        oneOf:
          - type: string
          - type: number
        default: 1
      unit:
        $ref: "./product-notice-unit.yaml"
        default: "hours"
  bookingPeriod:
    type: object
    properties:
      value:
        oneOf:
          - type: string
          - type: number
        default: 1
      unit:
        $ref: "./product-booking-unit.yaml"
        default: "months"

required:
  - productId
  - duration
  - breakTime
  - noticePeriod
  - bookingPeriod
