type: object
properties:
  productId:
    type: number
  visible:
    type: boolean
  duration:
    type: number
  breakTime:
    type: number
  noticePeriod:
    type: object
    properties:
      value:
        type: number
        default: 1
      unit:
        $ref: "./product-notice-unit.yaml"
        default: "hours"
  bookingPeriod:
    type: object
    properties:
      value:
        type: number
        default: 1
      unit:
        $ref: "./product-booking-unit.yaml"
        default: "months"

required:
  - productId
  - visible
  - duration
  - breakTime
  - noticePeriod
  - bookingPeriod
