type: object
properties:
  productId:
    type: string
  visible:
    type: boolean
  duration:
    type: string
  breakTime:
    type: string
  noticePeriod:
    type: object
    properties:
      value:
        type: string
        default: 1
      unit:
        $ref: "./product-notice-unit.yaml"
        default: "hours"
  bookingPeriod:
    type: object
    properties:
      value:
        type: string
        default: 1
      unit:
        $ref: "./product-booking-unit.yaml"
        default: "months"

required:
  - productId
  - visible
  - duration
  - breakTime
  - noticePeriod
  - bookingPeriod
