export const orderWithfulfillmentAndRefunds = {
  id: 5874046992711,
  admin_graphql_api_id: "gid://shopify/Order/5874046992711",
  app_id: 31210962945,
  browser_ip: "176.89.108.222",
  buyer_accepts_marketing: true,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: "Z2NwLWV1cm9wZS13ZXN0MzowMUhINko1MFpFQlJWMTM1SFY5MjZUUktOMw",
  checkout_id: 42324827701575,
  checkout_token: "51210de099db2630837a9ff20d2d6ba6",
  client_details: {
    accept_language: "da-DK",
    browser_height: null,
    browser_ip: "176.89.108.222",
    browser_width: null,
    session_hash: null,
    user_agent:
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36",
  },
  closed_at: null,
  confirmation_number: "XP2J5MIG8",
  confirmed: true,
  contact_email: "test@soueidan.com",
  created_at: "2023-12-09T06:53:51+01:00",
  currency: "DKK",
  current_subtotal_price: "0.00",
  current_subtotal_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  current_total_additional_fees_set: null,
  current_total_discounts: "0.00",
  current_total_discounts_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  current_total_duties_set: null,
  current_total_price: "0.00",
  current_total_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  current_total_tax: "0.00",
  current_total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  customer_locale: "da-DK",
  device_id: null,
  discount_codes: [],
  email: "test@soueidan.com",
  estimated_taxes: false,
  financial_status: "paid",
  fulfillment_status: "fulfilled",
  landing_site: "/",
  landing_site_ref: null,
  location_id: null,
  merchant_of_record_app_id: null,
  name: "#1014",
  note: null,
  note_attributes: [],
  number: 14,
  order_number: 1014,
  order_status_url:
    "https://bysistersdk.myshopify.com/68240605458/orders/3886ff2088637150765aa513c246dc16/authenticate?key=f16c8779934ac083f2016d65899baa0e",
  original_total_additional_fees_set: null,
  original_total_duties_set: null,
  payment_gateway_names: [],
  phone: null,
  po_number: null,
  presentment_currency: "DKK",
  processed_at: "2023-12-09T06:53:50+01:00",
  reference: "95a2cd9dad9350a742e0ba7e30cf1b3c",
  referring_site: "",
  source_identifier: "95a2cd9dad9350a742e0ba7e30cf1b3c",
  source_name: "31210962945",
  source_url: null,
  subtotal_price: "0.00",
  subtotal_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  tags: "",
  tax_exempt: false,
  tax_lines: [],
  taxes_included: true,
  test: false,
  token: "3886ff2088637150765aa513c246dc16",
  total_discounts: "0.00",
  total_discounts_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  total_line_items_price: "0.00",
  total_line_items_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  total_outstanding: "0.00",
  total_price: "0.00",
  total_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  total_shipping_price_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  total_tax: "0.00",
  total_tax_set: {
    shop_money: { amount: "0.00", currency_code: "DKK" },
    presentment_money: { amount: "0.00", currency_code: "DKK" },
  },
  total_tip_received: "0.00",
  total_weight: 0,
  updated_at: "2023-12-09T07:28:46+01:00",
  user_id: null,
  billing_address: {
    first_name: "ja",
    address1: "Odensegade",
    phone: "25 12 33 12",
    city: "Østerbro",
    zip: "2100",
    province: null,
    country: "Denmark",
    last_name: "misa",
    address2: null,
    company: null,
    latitude: null,
    longitude: null,
    name: "ja misa",
    country_code: "DK",
    province_code: null,
  },
  customer: {
    id: 7123671482695,
    email: "test@soueidan.com",
    accepts_marketing: true,
    created_at: "2023-05-23T22:53:49+02:00",
    updated_at: "2023-12-09T06:53:51+01:00",
    first_name: "kunde",
    last_name: "soueidan",
    state: "invited",
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    email_marketing_consent: {
      state: "subscribed",
      opt_in_level: "single_opt_in",
      consent_updated_at: "2023-05-23T22:53:50+02:00",
    },
    sms_marketing_consent: null,
    tags: "",
    currency: "DKK",
    accepts_marketing_updated_at: "2023-05-23T22:53:50+02:00",
    marketing_opt_in_level: "single_opt_in",
    tax_exemptions: [],
    admin_graphql_api_id: "gid://shopify/Customer/7123671482695",
    default_address: {
      id: 9939867369799,
      customer_id: 7123671482695,
      first_name: "ja",
      last_name: "misa",
      company: null,
      address1: "Odensegade",
      address2: null,
      city: "Østerbro",
      province: null,
      country: "Denmark",
      zip: "2100",
      phone: "25 12 33 12",
      name: "ja misa",
      province_code: null,
      country_code: "DK",
      country_name: "Denmark",
      default: true,
    },
  },
  discount_applications: [],
  fulfillments: [
    {
      id: 5261544161607,
      admin_graphql_api_id: "gid://shopify/Fulfillment/5261544161607",
      created_at: "2023-12-09T07:26:14+01:00",
      location_id: 73854943506,
      name: "#1014.1",
      order_id: 5874046992711,
      origin_address: {},
      receipt: {},
      service: "manual",
      shipment_status: null,
      status: "cancelled",
      tracking_company: null,
      tracking_number: null,
      tracking_numbers: [],
      tracking_url: null,
      tracking_urls: [],
      updated_at: "2023-12-09T07:28:34+01:00",
      line_items: [
        {
          id: 15174509134151,
          admin_graphql_api_id: "gid://shopify/LineItem/15174509134151",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Biotin og Capilia Longa",
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          product_exists: true,
          product_id: 8420509614407,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Biotin og Capilia Longa",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          variant_id: 46740488290631,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "BySisters",
          tax_lines: [
            {
              channel_liable: false,
              price: "0.00",
              price_set: {
                shop_money: { amount: "0.00", currency_code: "DKK" },
                presentment_money: { amount: "0.00", currency_code: "DKK" },
              },
              rate: 0.25,
              title: "DK Moms",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 15174509166919,
          admin_graphql_api_id: "gid://shopify/LineItem/15174509166919",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Børneklip (fra 6 år) - Artist 0",
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          product_exists: true,
          product_id: 8022088646930,
          properties: [
            { name: "_from", value: "2023-12-18T07:00:00.000Z" },
            { name: "_to", value: "2023-12-18T08:15:00.000Z" },
            { name: "_customerId", value: "7106990342471" },
            { name: "_locationId", value: "" },
            { name: "Tid", value: "mandag, 18. december  10:00" },
            { name: "Varighed", value: "1 time(r)" },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: false,
          title: "Børneklip (fra 6 år)",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          variant_id: 46727191036231,
          variant_inventory_management: null,
          variant_title: "Artist 0",
          vendor: "By Sisters",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
      ],
    },
    {
      id: 5261544259911,
      admin_graphql_api_id: "gid://shopify/Fulfillment/5261544259911",
      created_at: "2023-12-09T07:26:22+01:00",
      location_id: 73854943506,
      name: "#1014.2",
      order_id: 5874046992711,
      origin_address: {},
      receipt: {},
      service: "manual",
      shipment_status: null,
      status: "success",
      tracking_company: null,
      tracking_number: null,
      tracking_numbers: [],
      tracking_url: null,
      tracking_urls: [],
      updated_at: "2023-12-09T07:26:22+01:00",
      line_items: [
        {
          id: 15174509101383,
          admin_graphql_api_id: "gid://shopify/LineItem/15174509101383",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Brudemakeup - Artist 0",
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          product_exists: true,
          product_id: 8022088745234,
          properties: [
            { name: "_from", value: "2024-01-01T06:15:00.000Z" },
            { name: "_to", value: "2024-01-01T07:30:00.000Z" },
            { name: "_customerId", value: "7106990342471" },
            { name: "Skønhedsekspert", value: "hana nielsen" },
            { name: "Tid", value: "mandag, 1. januar  09:15" },
            { name: "Varighed", value: "1 time(r)" },
          ],
          quantity: 1,
          requires_shipping: false,
          sku: "",
          taxable: false,
          title: "Brudemakeup",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          variant_id: 48807163691335,
          variant_inventory_management: null,
          variant_title: "Artist 0",
          vendor: "By Sisters",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
      ],
    },
    {
      id: 5261545439559,
      admin_graphql_api_id: "gid://shopify/Fulfillment/5261545439559",
      created_at: "2023-12-09T07:28:46+01:00",
      location_id: 73854943506,
      name: "#1014.3",
      order_id: 5874046992711,
      origin_address: {},
      receipt: {},
      service: "manual",
      shipment_status: null,
      status: "success",
      tracking_company: null,
      tracking_number: null,
      tracking_numbers: [],
      tracking_url: null,
      tracking_urls: [],
      updated_at: "2023-12-09T07:28:46+01:00",
      line_items: [
        {
          id: 15174509134151,
          admin_graphql_api_id: "gid://shopify/LineItem/15174509134151",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Biotin og Capilia Longa",
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          product_exists: true,
          product_id: 8420509614407,
          properties: [],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: true,
          title: "Biotin og Capilia Longa",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          variant_id: 46740488290631,
          variant_inventory_management: "shopify",
          variant_title: null,
          vendor: "BySisters",
          tax_lines: [
            {
              channel_liable: false,
              price: "0.00",
              price_set: {
                shop_money: { amount: "0.00", currency_code: "DKK" },
                presentment_money: { amount: "0.00", currency_code: "DKK" },
              },
              rate: 0.25,
              title: "DK Moms",
            },
          ],
          duties: [],
          discount_allocations: [],
        },
        {
          id: 15174509166919,
          admin_graphql_api_id: "gid://shopify/LineItem/15174509166919",
          fulfillable_quantity: 0,
          fulfillment_service: "manual",
          fulfillment_status: "fulfilled",
          gift_card: false,
          grams: 0,
          name: "Børneklip (fra 6 år) - Artist 0",
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          product_exists: true,
          product_id: 8022088646930,
          properties: [
            { name: "_from", value: "2023-12-18T07:00:00.000Z" },
            { name: "_to", value: "2023-12-18T08:15:00.000Z" },
            { name: "_customerId", value: "7106990342471" },
            { name: "Skønhedsekspert", value: "hana nielsen" },
            { name: "Tid", value: "mandag, 18. december  10:00" },
            { name: "Varighed", value: "1 time(r)" },
          ],
          quantity: 1,
          requires_shipping: true,
          sku: "",
          taxable: false,
          title: "Børneklip (fra 6 år)",
          total_discount: "0.00",
          total_discount_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          variant_id: 46727191036231,
          variant_inventory_management: null,
          variant_title: "Artist 0",
          vendor: "By Sisters",
          tax_lines: [],
          duties: [],
          discount_allocations: [],
        },
      ],
    },
  ],
  line_items: [
    {
      id: 15174509101383,
      admin_graphql_api_id: "gid://shopify/LineItem/15174509101383",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Brudemakeup - Artist 0",
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      product_exists: true,
      product_id: 8022088745234,
      properties: [
        { name: "_from", value: "2024-01-01T06:15:00.000Z" },
        { name: "_to", value: "2024-01-01T07:30:00.000Z" },
        { name: "_customerId", value: "7106990342471" },
        { name: "Skønhedsekspert", value: "hana nielsen" },
        { name: "Tid", value: "mandag, 1. januar  09:15" },
        { name: "Varighed", value: "1 time(r)" },
      ],
      quantity: 1,
      requires_shipping: false,
      sku: "",
      taxable: false,
      title: "Brudemakeup",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      variant_id: 48807163691335,
      variant_inventory_management: null,
      variant_title: "Artist 0",
      vendor: "By Sisters",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 15174509134151,
      admin_graphql_api_id: "gid://shopify/LineItem/15174509134151",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Biotin og Capilia Longa",
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      product_exists: true,
      product_id: 8420509614407,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: "",
      taxable: true,
      title: "Biotin og Capilia Longa",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      variant_id: 46740488290631,
      variant_inventory_management: "shopify",
      variant_title: null,
      vendor: "BySisters",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          rate: 0.25,
          title: "DK Moms",
        },
      ],
      duties: [],
      discount_allocations: [],
    },
    {
      id: 15174509166919,
      admin_graphql_api_id: "gid://shopify/LineItem/15174509166919",
      fulfillable_quantity: 0,
      fulfillment_service: "manual",
      fulfillment_status: "fulfilled",
      gift_card: false,
      grams: 0,
      name: "Børneklip (fra 6 år) - Artist 0",
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      product_exists: true,
      product_id: 8022088646930,
      properties: [
        { name: "_from", value: "2023-12-18T07:00:00.000Z" },
        { name: "_to", value: "2023-12-18T08:15:00.000Z" },
        { name: "_customerId", value: "7106990342471" },
        { name: "Skønhedsekspert", value: "hana nielsen" },
        { name: "Tid", value: "mandag, 18. december  10:00" },
        { name: "Varighed", value: "1 time(r)" },
      ],
      quantity: 1,
      requires_shipping: true,
      sku: "",
      taxable: false,
      title: "Børneklip (fra 6 år)",
      total_discount: "0.00",
      total_discount_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      variant_id: 46727191036231,
      variant_inventory_management: null,
      variant_title: "Artist 0",
      vendor: "By Sisters",
      tax_lines: [],
      duties: [],
      discount_allocations: [],
    },
  ],
  payment_terms: null,
  refunds: [
    {
      id: 990883873095,
      admin_graphql_api_id: "gid://shopify/Refund/990883873095",
      created_at: "2023-12-09T07:27:01+01:00",
      note: "test",
      order_id: 5874046992711,
      processed_at: "2023-12-09T07:27:01+01:00",
      restock: true,
      total_duties_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      user_id: 87791010066,
      order_adjustments: [],
      transactions: [],
      refund_line_items: [
        {
          id: 654354776391,
          line_item_id: 15174509101383,
          location_id: 73854943506,
          quantity: 1,
          restock_type: "return",
          subtotal: 0,
          subtotal_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          total_tax: 0,
          total_tax_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          line_item: {
            id: 15174509101383,
            admin_graphql_api_id: "gid://shopify/LineItem/15174509101383",
            fulfillable_quantity: 0,
            fulfillment_service: "manual",
            fulfillment_status: "fulfilled",
            gift_card: false,
            grams: 0,
            name: "Brudemakeup - Artist 0",
            price: "0.00",
            price_set: {
              shop_money: { amount: "0.00", currency_code: "DKK" },
              presentment_money: { amount: "0.00", currency_code: "DKK" },
            },
            product_exists: true,
            product_id: 8022088745234,
            properties: [
              { name: "_from", value: "2024-01-01T06:15:00.000Z" },
              { name: "_to", value: "2024-01-01T07:30:00.000Z" },
              { name: "_customerId", value: "7106990342471" },
              { name: "Skønhedsekspert", value: "hana nielsen" },
              { name: "Tid", value: "mandag, 1. januar  09:15" },
              { name: "Varighed", value: "1 time(r)" },
            ],
            quantity: 1,
            requires_shipping: false,
            sku: "",
            taxable: false,
            title: "Brudemakeup",
            total_discount: "0.00",
            total_discount_set: {
              shop_money: { amount: "0.00", currency_code: "DKK" },
              presentment_money: { amount: "0.00", currency_code: "DKK" },
            },
            variant_id: 48807163691335,
            variant_inventory_management: null,
            variant_title: "Artist 0",
            vendor: "By Sisters",
            tax_lines: [],
            duties: [],
            discount_allocations: [],
          },
        },
      ],
      duties: [],
    },
  ],
  shipping_address: {
    first_name: "ja",
    address1: "Odensegade",
    phone: "25 12 33 12",
    city: "Østerbro",
    zip: "2100",
    province: null,
    country: "Denmark",
    last_name: "misa",
    address2: null,
    company: null,
    latitude: 55.7001114,
    longitude: 12.5807326,
    name: "ja misa",
    country_code: "DK",
    province_code: null,
  },
  shipping_lines: [
    {
      id: 4957849485639,
      carrier_identifier: "0c9403206891a20ecd54cf28f40ddb5b",
      code: "backup_rate",
      discounted_price: "0.00",
      discounted_price_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      phone: null,
      price: "0.00",
      price_set: {
        shop_money: { amount: "0.00", currency_code: "DKK" },
        presentment_money: { amount: "0.00", currency_code: "DKK" },
      },
      requested_fulfillment_service_id: null,
      source: "merchant_customized_by_order_value",
      title: "Levering",
      tax_lines: [
        {
          channel_liable: false,
          price: "0.00",
          price_set: {
            shop_money: { amount: "0.00", currency_code: "DKK" },
            presentment_money: { amount: "0.00", currency_code: "DKK" },
          },
          rate: 0.25,
          title: "DK Moms",
        },
      ],
      discount_allocations: [],
    },
  ],
};
