parameters:
  - name: id
    in: path
    description: The ID of the product
    required: true
    schema:
      type: string

put:
  $ref: "./update/index.yaml#/put"
get:
  $ref: "./get-by-id/index.yaml#/get"
