openapi: 3.0.2
info:
  version: 1.0.0
  title: Booking Shopify Api
  license:
    name: MIT
    url: 'http://'
  contact:
    name: jamal Soueidan
    email: jamal@soueidan.com
    url: 'https://github.com/jamalsoueidan'
  x-tagGroups:
    - name: all api endpoints
      tags:
        - Schedule
servers:
  - url: 'https://booking-shopify-api.azurewebsites.net/api'
components:
  responses:
    BadResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    ForbiddenResponse:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    NotFoundResponse:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
    UnauthorizedResponse:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  schemas:
    Errors:
      type: object
      properties:
        success:
          type: boolean
          example: false
        errors:
          type: array
          items:
            type: object
            properties:
              path:
                type: array
                items:
                  type: string
              message:
                type: string
              code:
                type: string
              expected:
                type: string
              received:
                type: number
            required:
              - path
              - message
              - code
      required:
        - success
        - errors
    User:
      type: object
      properties:
        customerId:
          type: string
        title:
          type: string
        username:
          type: string
          pattern: '^[a-zA-Z0-9-_]+$'
        fullname:
          type: string
        description:
          type: string
        social_urls:
          type: object
          properties:
            youtube:
              type: string
            twitter:
              type: string
            instagram:
              type: string
        active:
          type: string
        avatar:
          type: string
          format: uri
        speaks:
          type: array
          items:
            type: string
      required:
        - customerId
        - title
        - fullname
        - avatar
        - speaks
        - active
        - social_urls
        - description
    Destroy:
      type: object
      properties:
        deletedCount:
          type: number
        acknowledged:
          type: boolean
      required:
        - deletedCount
        - acknowledged
    Day:
      type: string
      enum:
        - monday
        - tuesday
        - wednesday
        - thursday
        - friday
        - saturday
        - sunday
    Interval:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
      required:
        - from
        - to
    Slot:
      type: object
      properties:
        day:
          $ref: '#/components/schemas/Day'
        intervals:
          type: array
          items:
            $ref: '#/components/schemas/Interval'
      required:
        - day
        - intervals
    Product:
      type: object
      properties:
        productId:
          type: number
        visible:
          type: boolean
        duration:
          type: number
        breakTime:
          type: number
      required:
        - productId
        - visible
        - duration
        - breakTime
    Schedule:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        customerId:
          type: number
        slots:
          type: array
          items:
            $ref: '#/components/schemas/Slot'
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
      required:
        - _id
        - name
        - customerId
        - slots
        - products
    ScheduleCreateBody:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    ScheduleCreateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Schedule'
      required:
        - success
        - payload
    ScheduleDestroyResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Destroy'
      required:
        - success
        - payload
    ScheduleListResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
      required:
        - success
        - payload
    ScheduleGetResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Schedule'
      required:
        - success
        - payload
    ScheduleUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Schedule'
      required:
        - success
        - payload
    ScheduleUpdateBody:
      type: object
      properties:
        name:
          type: string
      required:
        - name
    ScheduleSlotsUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Schedule'
      required:
        - success
        - payload
    ScheduleSlotsUpdateBody:
      type: array
      items:
        $ref: '#/components/schemas/Slot'
    ScheduleProductCreateOrUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Product'
      required:
        - success
        - payload
    ScheduleProductCreateOrUpdateBody:
      type: object
      properties:
        visible:
          type: boolean
        duration:
          type: number
        breakTime:
          type: number
      required:
        - visible
        - duration
        - breakTime
    ScheduleProductDestroyResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Destroy'
      required:
        - success
        - payload
    ScheduleProductGetResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/Product'
      required:
        - success
        - payload
    UserCreateOrUpdateResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/User'
      required:
        - success
        - payload
    UserCreateOrUpdateBody:
      type: object
      properties:
        title:
          type: string
        username:
          type: string
          pattern: '^[a-zA-Z0-9-_]+$'
        fullname:
          type: string
        description:
          type: string
        social_urls:
          type: object
          properties:
            youtube:
              type: string
            twitter:
              type: string
            instagram:
              type: string
        active:
          type: string
        avatar:
          type: string
          format: uri
        speaks:
          type: array
          items:
            type: string
      required:
        - fullname
        - avatar
    UserGetResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        payload:
          $ref: '#/components/schemas/User'
      required:
        - success
        - payload
paths:
  '/customer/{customerId}':
    parameters:
      - name: customerId
        in: query
        description: get by customerId
        required: true
        schema:
          type: string
    get:
      tags:
        - User
      operationId: userGetById
      summary: GET Get user
      description: This endpoint gets user object
      responses:
        '200':
          description: Response with payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGetResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
    put:
      tags:
        - User
      operationId: userCreateOrUpdate
      summary: PUT Create or Update user
      description: This endpoint creates new or updates user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateOrUpdateBody'
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateOrUpdateResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
      security: []
  '/customer/{customerId}/schedule':
    parameters:
      - name: customerId
        in: path
        description: The ID of the customerId
        required: true
        schema:
          type: string
    post:
      tags:
        - Schedule
      operationId: customerScheduleCreate
      summary: POST Create schedule
      description: This endpoint create new schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleCreateBody'
      responses:
        '200':
          description: Response with schedule payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleCreateResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
  '/customer/{customerId}/schedules':
    parameters:
      - name: customerId
        in: path
        description: The ID of the customerId
        required: true
        schema:
          type: string
    get:
      tags:
        - Schedule
      operationId: customerScheduleList
      summary: GET Get all schedule for customer
      description: This endpoint get all schedule for customer
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleListResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
      security: []
  '/customer/{customerId}/schedule/{scheduleId}':
    parameters:
      - name: customerId
        in: path
        description: The ID of the customerId
        required: true
        schema:
          type: string
      - name: scheduleId
        in: path
        description: The ID of the scheduleId
        required: true
        schema:
          type: string
    get:
      tags:
        - Schedule
      operationId: customerScheduleGet
      summary: GET Get schedule for customer
      description: This endpoint get schedule for customer
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleGetResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
      security: []
    put:
      tags:
        - Schedule
      operationId: customerScheduleUpdate
      summary: POST Update schedule
      description: This endpoint update schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleUpdateBody'
      responses:
        '200':
          description: Response with schedule payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleUpdateResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
    delete:
      tags:
        - Schedule
      operationId: customerScheduleDestroy
      summary: GET destroy schedule
      description: This endpoint destroy schedule for customer
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDestroyResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
      security: []
  '/customer/{customerId}/schedule/{scheduleId}/slots':
    parameters:
      - name: customerId
        in: path
        description: The ID of the customerId
        required: true
        schema:
          type: string
      - name: scheduleId
        in: path
        description: The ID of the scheduleId
        required: true
        schema:
          type: string
    put:
      tags:
        - Slot
      operationId: customerScheduleSlotUpdate
      summary: PUT Update schedule slot
      description: This endpoint update schedule slot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleSlotsUpdateBody'
      responses:
        '200':
          description: Response with schedule payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleSlotsUpdateResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
  '/customer/{customerId}/schedule/{scheduleId}/product/{productId}':
    parameters:
      - name: customerId
        in: path
        description: The ID of the customerId
        required: true
        schema:
          type: string
      - name: scheduleId
        in: path
        description: The ID of the scheduleId
        required: true
        schema:
          type: string
      - name: productId
        in: path
        description: The ID of the productId
        required: true
        schema:
          type: string
    get:
      tags:
        - Product
      operationId: customerScheduleProductGet
      summary: GET Get schedule product for customer
      description: This endpoint get schedule product for customer
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleProductGetResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
    put:
      tags:
        - Product
      operationId: customerScheduleProductCreateOrUpdate
      summary: PUT Create OR Update schedule product
      description: This endpoint update schedule product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleProductCreateOrUpdateBody'
      responses:
        '200':
          description: Response with schedule product payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleProductCreateOrUpdateResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
    delete:
      tags:
        - Product
      operationId: customerScheduleProductDestroy
      summary: GET destroy schedule product
      description: This endpoint destroy schedule product for customer
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleProductDestroyResponse'
        '400':
          $ref: '#/components/responses/BadResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
      security: []
tags:
  - name: Schedule
    description: Schedule
