parameters:
  - name: customerId
    in: path
    required: true
    schema:
      type: string
  - name: productId
    in: path
    required: true
    schema:
      type: string

get:
  $ref: "./get/index.yaml#/get"
put:
  $ref: "./update/index.yaml#/put"
post:
  $ref: "./add/index.yaml#/post"
delete:
  $ref: "./destroy/index.yaml#/delete"
