name: Bundle and Commit

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: ./.github/actions/checkout
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Node.js
      uses: ./.github/actions/setup-node
      with:
        node-version: 14

    - name: Install dependencies and run bundle
      run: |
        npm ci
        npm run bundle

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Bundle and commit updated code" || exit 0
        git push origin ${{ github.head_ref }}
