name: Bundle openapi.yml and validate openapi definition

on:
  pull_request:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies and run bundle openapi
        run: |
          npm ci
          npm run bundle-openapi
          npm run validate-openapi
